import { Injectable, Logger } from '@nestjs/common';

export interface CompileResult {
  summary: string;
  category: string;
  tags: string[];
  keyConcepts: string[];
  links: string[];
  content: string;
}

@Injectable()
export class LlmService {
  private readonly logger = new Logger(LlmService.name);

  /**
   * Mock method to simulate LLM compiling raw text into structured data.
   */
  async compileText(rawText: string, existingPages: string[] = []): Promise<CompileResult> {
    this.logger.log('Mocking LLM compilation process...');

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Mock response based on simple heuristics or just return fixed data for now
    let category = 'concepts';
    if (rawText.toLowerCase().includes('react') || rawText.toLowerCase().includes('node')) category = 'dev';
    if (rawText.toLowerCase().includes('architecture') || rawText.toLowerCase().includes('design')) category = 'architecture';

    const mockResult: CompileResult = {
      summary: 'This is an AI-generated summary of the provided text. It covers the main topics concisely.',
      category: category,
      tags: ['#type/raw', `#dev/${category}`],
      keyConcepts: ['Concept A', 'Concept B'],
      links: existingPages.length > 0 ? [existingPages[0]] : [],
      content: 'Here is the detailed structured content generated by the AI based on the raw input text.\n\n### Main Points\n- Point 1\n- Point 2',
    };

    return mockResult;
  }

  /**
   * Mock method to simulate embedding generation.
   * Returns a fake 1536-dimensional array.
   */
  async generateEmbedding(text: string): Promise<number[]> {
    this.logger.log('Mocking embedding generation...');

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 300));

    // Return a dummy array of 1536 floats
    const embedding = new Array(1536).fill(0).map(() => Math.random());
    return embedding;
  }
}
